config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :hearts, only: :create

  get '/about' => 'pages#about'

  root 'pages#welcome'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/heart.rb
class Heart < ApplicationRecord
	belongs_to :post
	validates :post_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :hearts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hearts_controller.rb
class HeartsController < ApplicationController
	def create
		@heart = Heart.new(heart_params)
    	if @heart.save
      		redirect_to @heart.post, notice: 'Hearted that post!'
    	else
      		redirect_to root_url, notice: "Had an issue creating that heart."
    	end
	end

	private
		# Never trust parameters from the scary internet, only allow the white list through.
    	def heart_params
      		params.require(:heart).permit(:post_id)
    	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def welcome
  	@posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_path, notice: 'Post was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :kind, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crumblr</title>
    <%= csrf_meta_tags %>

    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
  		<div class="page-header">
   			<ul class="nav nav-pills pull-right">
  				<li>
  					<%= link_to "Home", root_path %>
  				</li>

          <li>
            <%= link_to "Manage Posts", posts_path %>
          </li>
	
  				<li>
  					<%= link_to "About", about_path %>
  				</li>
  			</ul>

  			<h1>
  				<%= link_to 'crumblr', '/' %>
  				<small>// home baked goodness</small>
  			</h1>
  		</div>
			
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
    			<%= yield %>
    		</div>
    	</div>
	</div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

<p>
	This app was built using Ruby on Rails, and following link is my another website. <%= link_to "Ruby on Rails practice", "http://www.giniejin.com/Final-Web2/" %>
</p>

app/views/pages/welcome.html.erb
<% @posts.each do |post| %>
	<%= render 'posts/post', post: post %>
	<br><br><br>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <div class="field form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :kind %>
    <%= f.select :kind, ["text", "image"], {}, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>

  <div class="actions form-group">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="panel panel-default">
	<div class="panel-heading" style="margin: 0; padding: 20px; position: relative">
		<div class="pull-right">
			<%= form_for(Heart.new) do |f| %>
				<%= f.hidden_field :post_id, value: post.id %>
				<%= f.submit "♥", class: 'btn btn-danger', style: 'position: absolute; top: 50%; transform: translateY(-50%); right: 15px' %>
			<% end %>
		</div>
		<h4 style="margin: 0">
			<!--<strong>Title:</strong>-->
			<%= link_to post.title, post %>
		</h4>
	</div>

	<div class="panel-body">
		<p>
			<strong>Content:</strong>
			<% if post.kind == 'image' %>
				<%= image_tag post.content, style: 'width: 100%' %>
			<% else %>
				<%= simple_format post.content %>
			<% end %>
		</p>
		<p class="text-muted">
			<small>
				<%= post.created_at.to_formatted_s(:long) %>
			</small>

			<small class="pull-right">
				<%= post.hearts.count %> hearts
			</small>
		</p>
	</div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th class="col-md-3">Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td class="col-md-3"><%= post.title %></td>
        <td><%= truncate(post.content, length: 100) %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% if notice.present? %>
	<p class="alert alert-info">
		<%= notice %>
	</p>
<% end %>

<%= link_to 'Back', root_path %>

<%= render 'post', post: @post %>